# -*- coding: utf-8 -*-
"""MBN_Finances_Clasificacion_Categorizacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19BQOwV4c-oNxyUfVJC0qiOT4IyOVH6SF
"""

# Importar las bibliotecas
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score

# Frases
frases = [
    # Vivienda
    "renta", "hipoteca", "alquiler", "departamento", "casa", "pago mensual", "servicios", "luz", "agua", "gas",
    "mantenimiento", "reparación", "amueblado", "condominio", "seguro de hogar", "calefacción", "electricidad", "internet",
    "televisión por cable", "limpieza", "inmobiliaria", "comisión", "garantía", "redecoración", "mudanza",

    # Transporte
    "gasolina", "pasaje", "transporte público", "boleto", "taxi", "uber", "metro", "autobús", "tren", "bicicleta",
    "mantenimiento del auto", "llantas", "aceite", "lavado de auto", "peaje", "combustible", "estacionamiento", "multas",
    "carga eléctrica", "seguro del auto", "licencia de conducir", "verificación", "tarjeta de circulación", "asistencia vial",
    "viaje en barco",

    # Alimentación
    "comida", "frutas", "verduras", "carne", "pan", "lácteos", "arroz", "pasta", "cereal", "legumbres", "aceite", "sal",
    "azúcar", "bebidas", "jugos", "refrescos", "merienda", "desayuno", "almuerzo", "cena", "sándwich", "ensalada", "platos preparados",
    "tortillas", "galletas",

    # Salud y bienestar
    "medicina", "consultorio", "tratamiento", "doctor", "enfermero", "hospital", "emergencia", "cirugía", "receta médica", "vacunas",
    "examen médico", "dieta", "psicólogo", "terapia", "gimnasio", "nutrición", "fitness", "yoga", "meditación", "ejercicio",
    "vitaminas", "salud mental", "estudios médicos", "rehabilitación", "atención médica",

    # Ropa y calzado
    "camisa", "pantalón", "falda", "zapatos", "botas", "chaqueta", "abrigo", "sombrero", "bufanda", "guantes", "jeans", "blusa",
    "pijamas", "ropa interior", "sudadera", "zapatillas", "sandalias", "billetera", "cinturón", "camiseta", "pantalones cortos",
    "tenis", "mocasines", "bufanda", "gorro",

    # Educación
    "escuela", "universidad", "curso", "libros", "tarea", "examen", "profesor", "alumno", "materia", "carrera", "estudios",
    "educación infantil", "bachillerato", "maestría", "doctorado", "tesis", "calificación", "beca", "programa educativo",
    "colegio", "campus", "biblioteca", "tutoría", "evaluación", "clase",

    # Entretenimiento
    "película", "serie", "música", "videojuego", "teatro", "concierto", "libro", "lectura", "cómic", "evento", "fiesta", "juego",
    "diversión", "discoteca", "cine", "paseo", "espectáculo", "fútbol", "basketball", "tenis", "gimnasia", "baile", "parque",
    "museo", "exposición",

    # Tecnología
    "computadora", "teléfono", "smartphone", "tablet", "internet", "wifi", "red social", "programa", "software", "aplicación",
    "hardware", "videojuego", "pantalla", "teclado", "ratón", "cámara", "pantalla táctil", "disco duro", "memoria", "USB",
    "cargador", "batería", "innovación", "gadget", "redes inalámbricas",
]

# Categorías
categorias = [
    # Vivienda
    "Vivienda", "Vivienda", "Vivienda", "Vivienda", "Vivienda", "Vivienda", "Vivienda", "Vivienda", "Vivienda", "Vivienda",
    "Vivienda", "Vivienda", "Vivienda", "Vivienda", "Vivienda", "Vivienda", "Vivienda", "Vivienda", "Vivienda", "Vivienda",
    "Vivienda", "Vivienda", "Vivienda", "Vivienda", "Vivienda",

    # Transporte
    "Transporte", "Transporte", "Transporte", "Transporte", "Transporte", "Transporte", "Transporte", "Transporte", "Transporte", "Transporte",
    "Transporte", "Transporte", "Transporte", "Transporte", "Transporte", "Transporte", "Transporte", "Transporte", "Transporte", "Transporte",
    "Transporte", "Transporte", "Transporte", "Transporte", "Transporte",

    # Alimentación
    "Alimentación", "Alimentación", "Alimentación", "Alimentación", "Alimentación", "Alimentación", "Alimentación", "Alimentación", "Alimentación", "Alimentación",
    "Alimentación", "Alimentación", "Alimentación", "Alimentación", "Alimentación", "Alimentación", "Alimentación", "Alimentación", "Alimentación", "Alimentación",
    "Alimentación", "Alimentación", "Alimentación", "Alimentación", "Alimentación",

    # Salud y bienestar
    "Salud y bienestar", "Salud y bienestar", "Salud y bienestar", "Salud y bienestar", "Salud y bienestar", "Salud y bienestar", "Salud y bienestar", "Salud y bienestar",
    "Salud y bienestar", "Salud y bienestar", "Salud y bienestar", "Salud y bienestar", "Salud y bienestar", "Salud y bienestar", "Salud y bienestar", "Salud y bienestar",
    "Salud y bienestar", "Salud y bienestar", "Salud y bienestar", "Salud y bienestar", "Salud y bienestar", "Salud y bienestar", "Salud y bienestar", "Salud y bienestar",
    "Salud y bienestar",

    # Ropa y calzado
    "Ropa y calzado", "Ropa y calzado", "Ropa y calzado", "Ropa y calzado", "Ropa y calzado", "Ropa y calzado", "Ropa y calzado", "Ropa y calzado", "Ropa y calzado", "Ropa y calzado",
    "Ropa y calzado", "Ropa y calzado", "Ropa y calzado", "Ropa y calzado", "Ropa y calzado", "Ropa y calzado", "Ropa y calzado", "Ropa y calzado", "Ropa y calzado", "Ropa y calzado",
    "Ropa y calzado", "Ropa y calzado", "Ropa y calzado", "Ropa y calzado", "Ropa y calzado",

    # Educación
    "Educación", "Educación", "Educación", "Educación", "Educación", "Educación", "Educación", "Educación", "Educación", "Educación",
    "Educación", "Educación", "Educación", "Educación", "Educación", "Educación", "Educación", "Educación", "Educación", "Educación",
    "Educación", "Educación", "Educación", "Educación", "Educación",

    # Entretenimiento
    "Entretenimiento", "Entretenimiento", "Entretenimiento", "Entretenimiento", "Entretenimiento", "Entretenimiento", "Entretenimiento", "Entretenimiento", "Entretenimiento",
    "Entretenimiento", "Entretenimiento", "Entretenimiento", "Entretenimiento", "Entretenimiento", "Entretenimiento", "Entretenimiento", "Entretenimiento", "Entretenimiento",
    "Entretenimiento", "Entretenimiento", "Entretenimiento", "Entretenimiento", "Entretenimiento", "Entretenimiento", "Entretenimiento",

    # Tecnología
    "Tecnología", "Tecnología", "Tecnología", "Tecnología", "Tecnología", "Tecnología", "Tecnología", "Tecnología", "Tecnología", "Tecnología",
    "Tecnología", "Tecnología", "Tecnología", "Tecnología", "Tecnología", "Tecnología", "Tecnología", "Tecnología", "Tecnología", "Tecnología",
    "Tecnología", "Tecnología", "Tecnología", "Tecnología", "Tecnología"
]

# Vectorizar texto
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(frases)

y = categorias

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Entrenar modelo
model = MultinomialNB()
model.fit(X_train, y_train)

import joblib

joblib.dump(model, 'MBNFinances_ModelodeCategorizacionEntrenado.pkl')